version: '3'

services:
  backend:
    build:
      context: ./backend
    ports:
      - "3333:3333"
  
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

networks:
  default:
    driver: bridge

